### ISSUE TITLE
cannot open files

### ISSUE THREAD

**Issue by LittleTale** [three-houses-research-team/Progenitor#1]
don't want to sound like a noob but once i backup my fire emblem three houses file with Checkpoint and try to open them with Progenitor it does not recognize any files. they don't even have extentions and the app ask me for a .bin or .database ??

![progenitor](https://user-images.githubusercontent.com/52611040/99160017-32963c80-26a8-11eb-92ce-a50db43dc097.png)

**Comment by VelouriasMoon** [comment]
Progenitor is a file data editor not a save editor, you'll need to dump files from the game's 1.2.0 update. if you need help dumping the files check the [Throne of Knowledge ](https://github.com/three-houses-research-team/Throne-of-Knowledge/wiki), if you're looking for a check here [https://gbatemp.net/threads/fire-emblem-three-houses-general-hacking.544144/](https://gbatemp.net/threads/fire-emblem-three-houses-general-hacking.544144/)
